apiVersion: v1
kind: ConfigMap
metadata:
  name: envconfig
  namespace: production
data:
  DB_NAME: "kubernetes101db"
  DB_HOST: "terraform-20181102201911881300000001.ctrkthnoul1u.us-west-2.rds.amazonaws.com"
  RUN_IN_PRODUCTION: "True"
  AWS_S3_REGION_NAME: "us-west-2"


