kind: Service
apiVersion: v1
metadata:
  name: django-service
spec:
  selector:
    app: django
  # the loadbalancer type exposes the service outside k8s via a AWS ELB for example.
  # so, it makes it reachable from clients.
  # Different k8s providers have different LB implementations
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
